import datetime
from datetime import datetime, timedelta
import requests
from dataclasses import dataclass, field
from typing import List
import random


class ContentFetcher:
    def __init__(self, tmdb_api_key, nyt_api_key):
        self.tmdb_api_key = tmdb_api_key
        self.nyt_api_key = nyt_api_key

    def get_recent_movies(self, days_back=30):
        url = f'https://api.themoviedb.org/3/movie/now_playing?api_key={self.tmdb_api_key}'
        response = requests.get(url)
        if response.status_code == 200:
            return response.json()['results']
        return []

    def get_bestseller_books(self):
        url = f'https://api.nytimes.com/svc/books/v3/lists/current/hardcover-fiction.json?api_key={self.nyt_api_key}'
        response = requests.get(url)
        if response.status_code == 200:
            return response.json()['results']['books']
        return []


@dataclass
class Intro:
    def pick_random(self, pick_from: str = 'movies') -> str:
        """Pick a random item from the specified list."""
        if pick_from == 'song':
            return random.choice(self.songs)
        elif pick_from == 'book':
            return random.choice(self.books)
        elif pick_from == 'movie':
            return random.choice(self.movies)
        elif pick_from == 'tv_show':
            return random.choice(self.tv_shows)
        else:
            raise ValueError("Invalid list specified. Use 'books' or 'movies'.")

    songs: List[str] = field(default_factory=lambda: [
        "GPT listened to a song and generated the image above.\nWhat song inspired GPT?",
        "The image above was created by GPT after listening to a song.\nCan you guess which song inspired it?",
        "Inspired by a song, GPT crafted the image above.\nWhat song do you think it is?",
        "GPT transformed a song into the visual above.\nWhich song do you think it represents?",
        "After hearing a song, GPT imagined the image above.\nCan you name the song behind it?"
    ])
    books: List[str] = field(default_factory=lambda: [
        "GPT read a book and generated the image above.\nWhat book did GPT read?",
        "The image above was created by GPT after reading a book. Can you guess which book it was?",
        "Inspired by a book, GPT crafted the image above. Which book do you think it represents",
        "GPT transformed a book into the visual above. What book might have inspired it?",
        "After reading a book, GPT imagined the image above. Can you name the book?"
    ])
    movies: List[str] = field(default_factory=lambda: [
        "GPT watched a movie and generated the image above.\nWhat movie inspired GPT?",
        "The image above was created by GPT after watching a movie. Can you guess which movie inspired it?",
        "Inspired by a movie, GPT crafted the image above. What movie do you think it represents?",
        "GPT turned a movie into the visual above. Can you name the film that inspired it?",
        "After watching a movie, GPT imagined the image above. Which movie do you think it was?",
    ])
    tv_shows: List[str] = field(default_factory=lambda: [
        "GPT watched a TV show and generated the image above.\nWhat TV show did GPT watch?",
        "The image above was created by GPT after watching a TV show. Can you guess which one?",
        "Inspired by a TV show, GPT crafted the image above. What show do you think it represents?",
        "GPT transformed a TV show into the visual above. Can you name the series behind it?",
        "After watching a TV show, GPT imagined the image above. Which show might it have been?"
    ])


@dataclass
class Topic:
    def pick_random(self, pick_from: str = 'movies', n_options: int = 5) -> str:
        """Pick a random item from the specified list."""
        if pick_from == 'song':
            return random.sample(self.songs, n_options)
        elif pick_from == 'book':
            return random.sample(self.books, n_options)
        elif pick_from == 'movie':
            return random.sample(self.movies, n_options)
        elif pick_from == 'tv_show':
            return random.sample(self.tv_shows, n_options)
        else:
            raise ValueError("Invalid list specified. Use 'books' or 'movies'.")

    songs: List[str] = field(default_factory=lambda: [
                                "Bohemian Rhapsody (Queen)",
                                "Stairway to Heaven (Led Zeppelin)",
                                "Imagine (John Lennon)",
                                "Hey Jude (The Beatles)",
                                "Hotel California (Eagles)",
                                "Billie Jean (Michael Jackson)",
                                "Like a Rolling Stone (Bob Dylan)",
                                "Smells Like Teen Spirit (Nirvana)",
                                "What's Going On (Marvin Gaye)",
                                "Yesterday (The Beatles)",
                                "Purple Rain (Prince)",
                                "Thriller (Michael Jackson)",
                                "Born to Run (Bruce Springsteen)",
                                "Let It Be (The Beatles)",
                                "I Will Always Love You (Whitney Houston)",
                                "Shake It Off (Taylor Swift)",
                                "Someone Like You (Adele)",
                                "Shape of You (Ed Sheeran)",
                                "Hallelujah (Leonard Cohen)",
                                "No Woman, No Cry (Bob Marley & The Wailers)",
                                "Superstition (Stevie Wonder)",
                                "Good Vibrations (The Beach Boys)",
                                "Respect (Aretha Franklin)",
                                "My Heart Will Go On (Celine Dion)",
                                "Poker Face (Lady Gaga)",
                                "Uptown Funk (Mark Ronson ft. Bruno Mars)",
                                "Take On Me (A-ha)",
                                "Toxic (Britney Spears)",
                                "Wonderwall (Oasis)",
                                "We Will Rock You (Queen)",
                                "Shallow (Lady Gaga & Bradley Cooper)",
                                "All of Me (John Legend)",
                                "Thinking Out Loud (Ed Sheeran)",
                                "Yesterday Once More (Carpenters)",
                                "Rolling in My Sweet Baby’s Arms (Buck Owens)",
                                "Bad Guy (Billie Eilish)",
                                "Chandelier (Sia)",
                                "All I Want for Christmas Is You (Mariah Carey)",
                                "Despacito (Luis Fonsi ft. Daddy Yankee)",
                                "Gangnam Style (PSY)",
                                "Blinding Lights (The Weeknd)",
                                "Levitating (Dua Lipa)",
                                "Watermelon Sugar (Harry Styles)",
                                "Old Town Road (Lil Nas X)",
                                "Drivers License (Olivia Rodrigo)",
                                "Rockstar (Post Malone)",
                                "Hips Don’t Lie (Shakira ft. Wyclef Jean)",
                                "I Wanna Dance With Somebody (Whitney Houston)",
                                "Crazy in Love (Beyoncé ft. Jay-Z)",
                                "Rolling in the Deep (Adele)",
                                "Sweet Child o' Mine (Guns N' Roses)",
                                "Enter Sandman (Metallica)",
                                "Boulevard of Broken Dreams (Green Day)",
                                "Seven Nation Army (The White Stripes)",
                                "Lose Yourself (Eminem)",
                                "Stronger (Kanye West)",
                                "God’s Plan (Drake)",
                                "Hotline Bling (Drake)",
                                "Formation (Beyoncé)",
                                "WAP (Cardi B ft. Megan Thee Stallion)",
                                "Say My Name (Destiny’s Child)",
                                "Killing Me Softly With His Song (Fugees)",
                                "Iris (Goo Goo Dolls)",
                                "With or Without You (U2)",
                                "Viva La Vida (Coldplay)",
                                "Fix You (Coldplay)",
                                "Don't Stop Believin' (Journey)",
                                "Eye of the Tiger (Survivor)",
                                "Livin' on a Prayer (Bon Jovi)",
                                "We Are the Champions (Queen)",
                                "Dancing Queen (ABBA)",
                                "Mamma Mia (ABBA)",
                                "Waterloo (ABBA)",
                                "Piano Man (Billy Joel)",
                                "Tiny Dancer (Elton John)",
                                "Rocket Man (Elton John)",
                                "Candle in the Wind (Elton John)",
                                "Born in the U.S.A. (Bruce Springsteen)",
                                "The Times They Are A-Changin' (Bob Dylan)",
                                "California Dreamin' (The Mamas & The Papas)",
                                "Ain't No Mountain High Enough (Marvin Gaye & Tammi Terrell)",
                                "How Deep Is Your Love (Bee Gees)",
                                "I Want It That Way (Backstreet Boys)",
                                "Everybody (Backstreet Boys)",
                                "Bye Bye Bye (NSYNC)",
                                "Tears in Heaven (Eric Clapton)",
                                "Smooth (Santana ft. Rob Thomas)",
                                "I Gotta Feeling (The Black Eyed Peas)",
                                "Happy (Pharrell Williams)",
                                "Get Lucky (Daft Punk ft. Pharrell Williams)",
                                "Radioactive (Imagine Dragons)",
                                "Demons (Imagine Dragons)",
                                "Counting Stars (OneRepublic)",
                                "Apologize (Timbaland ft. OneRepublic)",
                                "Castle on the Hill (Ed Sheeran)",
                                "Perfect (Ed Sheeran)",
                                "Photograph (Ed Sheeran)",
                                "Redemption Song (Bob Marley)",
                                "A Change Is Gonna Come (Sam Cooke)",
                                "The Sound of Silence (Simon & Garfunkel)",
                                "Bridge Over Troubled Water (Simon & Garfunkel)",
                                "November Rain (Guns N' Roses)",
                                ])
    tv_shows: List[str] = field(default_factory=lambda: [
                                # Classics and influential shows
                                "The Sopranos (1999)",
                                "Breaking Bad (2008)",
                                "Game of Thrones (2011)",
                                "The Wire (2002)",
                                "Friends (1994)",
                                "Seinfeld (1989)",
                                "The Simpsons (1989)",
                                "M*A*S*H (1972)",
                                "The Twilight Zone (1959)",
                                "The X-Files (1993)",
                                "Mad Men (2007)",
                                "The West Wing (1999)",
                                "I Love Lucy (1951)",
                                "Cheers (1982)",
                                "Fargo (2014)",
                                "The Office US (2005)",
                                "The Office UK (2001)",
                                "Parks and Recreation (2009)",
                                "Lost (2004)",
                                "Six Feet Under (2001)",
                                # Sci-Fi & Fantasy
                                "Doctor Who (1963)",
                                "Star Trek The Original Series (1966)",
                                "Star Trek The Next Generation (1987)",
                                "Stranger Things (2016)",
                                "Battlestar Galactica (2004)",
                                "The Mandalorian (2019)",
                                "The Expanse (2015)",
                                "Westworld (2016)",
                                "Buffy the Vampire Slayer (1997)",
                                "Supernatural (2005)",
                                "The Sandman (2022)",
                                "Dark (2017)",
                                "The Witcher (2019)",
                                "Fringe (2008)",
                                "Firefly (2002)",
                                "Babylon 5 (1993)",
                                "Heroes (2006)",
                                "Smallville (2001)",
                                "Andor (2022)",
                                "Justice League",
                                # Comedy
                                "Arrested Development (2003)",
                                "Brooklyn Nine-Nine (2013)",
                                "30 Rock (2006)",
                                "Modern Family (2009)",
                                "How I Met Your Mother (2005)",
                                "The Big Bang Theory (2007)",
                                "Ted Lasso (2020)",
                                "Community (2009)",
                                "Freaks and Geeks (1999)",
                                "Schitt's Creek (2015)",
                                "Blackadder (1983)",
                                "The IT Crowd (2006)",
                                "Spaced (1999)",
                                "Flight of the Conchords (2007)",
                                "Mr. Bean (1990)",
                                # Crime & Thriller
                                "Sherlock (2010)",
                                "True Detective (2014)",
                                "Mindhunter (2017)",
                                "Hannibal (2013)",
                                "Dexter (2006)",
                                "Ozark (2017)",
                                "Killing Eve (2018)",
                                "Better Call Saul (2015)",
                                "Luther (2010)",
                                "Broadchurch (2013)",
                                "The Night Manager (2016)",
                                "Bodyguard (2018)",
                                "Twin Peaks (1990)",
                                "Columbo (1971)",
                                "The Family Man",
                                # Animated
                                "Avatar The Last Airbender (2005)",
                                "BoJack Horseman (2014)",
                                "Rick and Morty (2013)",
                                "Futurama (1999)",
                                "Gravity Falls (2012)",
                                "Adventure Time (2010)",
                                "Archer (2009)",
                                "Bob's Burgers (2011)",
                                "Samurai Jack (2001)",
                                "Castlevania (2017)",
                                "Invincible (2021)",
                                "Cyberpunk Edgerunners (2022)",
                                "The Legend of Korra (2012)",
                                "South Park (1997)",
                                "Naruto: Shippuden (2007)",
                                "Attack on Titan (2013)",
                                "Death Note (2006)",
                                # Drama
                                "Succession (2018)",
                                "The Crown (2016)",
                                "The Handmaid's Tale (2017)",
                                "Euphoria (2019)",
                                "Big Little Lies (2017)",
                                "The Americans (2013)",
                                "Downton Abbey (2010)",
                                "This Is Us (2016)",
                                "House of Cards (2013)",
                                "Yellowjackets (2021)",
                                "The Leftovers (2014)",
                                "Friday Night Lights (2006)",
                                "Skins UK (2007)",
                                "Shameless (2011)",
                                "Californication (2007)",
                                # Historical & Period
                                "Chernobyl (2019)",
                                "Rome (2005)",
                                "Band of Brothers (2001)",
                                "The Pacific (2010)",
                                "Deadwood (2004)",
                                "Vikings (2013)",
                                "The Last Kingdom (2015)",
                                "Outlander (2014)",
                                "Peaky Blinders (2013)",
                                "Call the Midwife (2012)",
                                "Poldark (2015)",
                                "Marco Polo (2014)",
                                "Shōgun (2024)",
                                "Pride and Prejudice (2005)",
                                # Mystery & Horror
                                "The Haunting of Hill House (2018)",
                                "The Haunting of Bly Manor (2020)",
                                "Midnight Mass (2021)",
                                "American Horror Story (2011)",
                                "The Walking Dead (2010)",
                                "The Terror (2018)",
                                "Penny Dreadful (2014)",
                                "Bates Motel (2013)",
                                "Strange Angel (2018)",
                                "Castle Rock (2018)",
                                # Non-English shows
                                "Money Heist La Casa de Papel (2017)",
                                "Squid Game (2021)",
                                "Dark (2017)",
                                "Borgen (2010)",
                                "Narcos (2015)",
                                "Narcos Mexico (2018)",
                                "Elite (2018)",
                                "The Bridge Bron Broen (2011)",
                                "Call My Agent Dix pour cent (2015)",
                                "Babylon Berlin (2017)",
                                # Additional
                                "Silicon Valley (2014)",
                                "Homeland (2011)",
                                "House (2004)",
                                "The Good Wife (2009)",
                                "The Good Place (2016)",
                                "Black Mirror (2011)",
                                "Better Things (2016)",
                                "Fleabag (2016)"
                                ])
    books: List[str] = field(default_factory=lambda: [
        "Don Quixote (Miguel de Cervantes)",
        "Alice's Adventures in Wonderland (Lewis Carroll)",
        "The Adventures of Huckleberry Finn (Mark Twain)",
        "The Adventures of Tom Sawyer (Mark Twain)",
        "Treasure Island (Robert Louis Stevenson)",
        "Pride and Prejudice (Jane Austen)",
        "Wuthering Heights (Emily Brontë)",
        "Jane Eyre (Charlotte Brontë)",
        "Moby Dick (Herman Melville)",
        "The Scarlet Letter (Nathaniel Hawthorne)",
        "Gulliver's Travels (Jonathan Swift)",
        "The Pilgrim's Progress (John Bunyan)",
        "A Christmas Carol (Charles Dickens)",
        "David Copperfield (Charles Dickens)",
        "A Tale of Two Cities (Charles Dickens)",
        "Little Women (Louisa May Alcott)",
        "Great Expectations (Charles Dickens)",
        "The Hobbit (J.R.R. Tolkien)",
        "Frankenstein (Mary Shelley)",
        "Oliver Twist (Charles Dickens)",
        "Uncle Tom's Cabin (Harriet Beecher Stowe)",
        "Crime and Punishment (Fyodor Dostoevsky)",
        "Madame Bovary (Gustave Flaubert)",
        "The Return of the King (J.R.R. Tolkien)",
        "Dracula (Bram Stoker)",
        "The Three Musketeers (Alexandre Dumas)",
        "Brave New World (Aldous Huxley)",
        "War and Peace (Leo Tolstoy)",
        "To Kill a Mockingbird (Harper Lee)",
        "The Wizard of Oz (L. Frank Baum)",
        "Les Misérables (Victor Hugo)",
        "The Secret Garden (Frances Hodgson Burnett)",
        "Animal Farm (George Orwell)",
        "The Great Gatsby (F. Scott Fitzgerald)",
        "The Little Prince (Antoine de Saint-Exupéry)",
        "The Call of the Wild (Jack London)",
        "20,000 Leagues Under the Sea (Jules Verne)",
        "Anna Karenina (Leo Tolstoy)",
        "The Wind in the Willows (Kenneth Grahame)",
        "The Picture of Dorian Gray (Oscar Wilde)",
        "The Grapes of Wrath (John Steinbeck)",
        "Sense and Sensibility (Jane Austen)",
        "The Last of the Mohicans (James Fenimore Cooper)",
        "Tess of the d'Urbervilles (Thomas Hardy)",
        "Harry Potter and the Sorcerer's Stone (J.K. Rowling)",
        "Heidi (Johanna Spyri)",
        "Ulysses (James Joyce)",
        "The Complete Sherlock Holmes (Arthur Conan Doyle)",
        "The Count of Monte Cristo (Alexandre Dumas)",
        "The Old Man and the Sea (Ernest Hemingway)",
        "The Lion, the Witch, and the Wardrobe (C.S. Lewis)",
        "The Hunchback of Notre Dame (Victor Hugo)",
        "Pinocchio (Carlo Collodi)",
        "One Hundred Years of Solitude (Gabriel García Márquez)",
        "Ivanhoe (Walter Scott)",
        "The Red Badge of Courage (Stephen Crane)",
        "Anne of Green Gables (L.M. Montgomery)",
        "Black Beauty (Anna Sewell)",
        "Peter Pan (J.M. Barrie)",
        "A Farewell to Arms (Ernest Hemingway)",
        "The House of the Seven Gables (Nathaniel Hawthorne)",
        "Lord of the Flies (William Golding)",
        "The Prince and the Pauper (Mark Twain)",
        "A Portrait of the Artist as a Young Man (James Joyce)",
        "Lord Jim (Joseph Conrad)",
        "Harry Potter and the Chamber of Secrets (J.K. Rowling)",
        "The Red & the Black (Stendhal)",
        "The Stranger (Albert Camus)",
        "The Trial (Franz Kafka)",
        "Lady Chatterley's Lover (D.H. Lawrence)",
        "Kidnapped (Robert Louis Stevenson)",
        "The Catcher in the Rye (J.D. Salinger)",
        "Fahrenheit 451 (Ray Bradbury)",
        "A Journey to the Center of the Earth (Jules Verne)",
        "Vanity Fair (William Makepeace Thackeray)",
        "All Quiet on the Western Front (Erich Maria Remarque)",
        "Gone with the Wind (Margaret Mitchell)",
        "My Ántonia (Willa Cather)",
        "Of Mice and Men (John Steinbeck)",
        "The Vicar of Wakefield (Oliver Goldsmith)",
        "A Connecticut Yankee in King Arthur's Court (Mark Twain)",
        "White Fang (Jack London)",
        "Fathers and Sons (Ivan Turgenev)",
        "Doctor Zhivago (Boris Pasternak)",
        "The Decameron (Giovanni Boccaccio)",
        "Nineteen Eighty-Four (George Orwell)",
        "The Jungle (Upton Sinclair)",
        "The Da Vinci Code (Dan Brown)",
        "Persuasion (Jane Austen)",
        "Mansfield Park (Jane Austen)",
        "Candide (Voltaire)",
        "For Whom the Bell Tolls (Ernest Hemingway)",
        "Far from the Madding Crowd (Thomas Hardy)",
        "The Fellowship of the Ring (J.R.R. Tolkien)",
        "The Return of the Native (Thomas Hardy)",
        "Sons and Lovers (D.H. Lawrence)",
        "Charlotte's Web (E.B. White)",
        "The Swiss Family Robinson (Johann David Wyss)",
        "Bleak House (Charles Dickens)",
        "Père Goriot (Honoré de Balzac)",
        "The Brothers Karamazov (Fyodor Dostoevsky)",
        "Middlemarch (George Eliot)",
        "Beloved (Toni Morrison)",
        "Lolita (Vladimir Nabokov)",
        "Catch-22 (Joseph Heller)",
        "The Sound and the Fury (William Faulkner)",
        "To the Lighthouse (Virginia Woolf)",
        "Mrs. Dalloway (Virginia Woolf)",
        "Invisible Man (Ralph Ellison)",
        "Slaughterhouse-Five (Kurt Vonnegut)",
        "A Passage to India (E.M. Forster)",
        "The Sun Also Rises (Ernest Hemingway)",
        "East of Eden (John Steinbeck)",
        "The Bell Jar (Sylvia Plath)",
        "The Road (Cormac McCarthy)",
        "Blood Meridian (Cormac McCarthy)",
        "Things Fall Apart (Chinua Achebe)",
        "The Handmaid's Tale (Margaret Atwood)",
        "Life of Pi (Yann Martel)",
        "The Alchemist (Paulo Coelho)",
        "One Flew Over the Cuckoo's Nest (Ken Kesey)",
        "The Kite Runner (Khaled Hosseini)",
        "The Book Thief (Markus Zusak)",
        "The Name of the Rose (Umberto Eco)",
        "The Glass Bead Game (Hermann Hesse)",
        "Steppenwolf (Hermann Hesse)",
        "Siddhartha (Hermann Hesse)",
        "If on a Winter's Night a Traveler (Italo Calvino)",
        "The Master and Margarita (Mikhail Bulgakov)",
        "The Unbearable Lightness of Being (Milan Kundera)",
        "Love in the Time of Cholera (Gabriel García Márquez)",
        "The Secret History (Donna Tartt)",
        "The Goldfinch (Donna Tartt)",
        "Cloud Atlas (David Mitchell)",
        "The Thousand Autumns of Jacob de Zoet (David Mitchell)",
        "Norwegian Wood (Haruki Murakami)",
        "Kafka on the Shore (Haruki Murakami)",
        "1Q84 (Haruki Murakami)",
        "A Wild Sheep Chase (Haruki Murakami)",
        "The Wind-Up Bird Chronicle (Haruki Murakami)",
        "The Catcher in the Rye (J.D. Salinger)",
        "The Stranger (Albert Camus)",
        "The Plague (Albert Camus)",
        "The Trial (Franz Kafka)",
        "Metamorphosis (Franz Kafka)",
        "Doctor Faustus (Thomas Mann)",
        "The Magic Mountain (Thomas Mann)",
        "A Confederacy of Dunces (John Kennedy Toole)",
        "The Blind Assassin (Margaret Atwood)",
        "Alias Grace (Margaret Atwood)",
        "The Night Circus (Erin Morgenstern)",
        "Jonathan Strange & Mr Norrell (Susanna Clarke)",
        "Good Omens (Neil Gaiman and Terry Pratchett)",
        "American Gods (Neil Gaiman)",
        "Neverwhere (Neil Gaiman)",
        "Stardust (Neil Gaiman)",
        "The Graveyard Book (Neil Gaiman)",
        "The Ocean at the End of the Lane (Neil Gaiman)",
        "Watership Down (Richard Adams)",
        "The Once and Future King (T.H. White)",
        "The Sword in the Stone (T.H. White)",
        "I, Claudius (Robert Graves)",
        "Claudius the God (Robert Graves)",
        "The Man in the High Castle (Philip K. Dick)",
        "Do Androids Dream of Electric Sheep? (Philip K. Dick)",
        "Neuromancer (William Gibson)",
        "Snow Crash (Neal Stephenson)",
        "Dune (Frank Herbert)",
        "Hyperion (Dan Simmons)",
        "The Left Hand of Darkness (Ursula K. Le Guin)",
        "Earthsea Trilogy (Ursula K. Le Guin)",
        "The Dispossessed (Ursula K. Le Guin)",
        "Parable of the Sower (Octavia E. Butler)",
        "Kindred (Octavia E. Butler)",
        "The Giver (Lois Lowry)",
        "Ender's Game (Orson Scott Card)",
        "Speaker for the Dead (Orson Scott Card)",
        "Foundation (Isaac Asimov)",
        "I, Robot (Isaac Asimov)",
        "1984 (George Orwell)",
        "Brave New World (Aldous Huxley)",
        "Fahrenheit 451 (Ray Bradbury)",
        "The Martian Chronicles (Ray Bradbury)",
        "The Illustrated Man (Ray Bradbury)",
        "The Golden Notebook (Doris Lessing)",
        "The Color Purple (Alice Walker)",
        "Their Eyes Were Watching God (Zora Neale Hurston)",
        "Song of Solomon (Toni Morrison)",
        "Tar Baby (Toni Morrison)",
        "The Bluest Eye (Toni Morrison)",
        "Beloved (Toni Morrison)",
        "Roadside Picnic (Arkady and Boris Strugatsky)",
        "Hard to Be a God (Arkady and Boris Strugatsky)",
        "The Doomed City (Arkady and Boris Strugatsky)",
        "Stranger in a Strange Land (Robert A. Heinlein)",
        "The Moon is a Harsh Mistress (Robert A. Heinlein)",
        "Starship Troopers (Robert A. Heinlein)",
        "Time Enough for Love (Robert A. Heinlein)",
        "Ubik (Philip K. Dick)",
        "A Scanner Darkly (Philip K. Dick)",
        "Flow My Tears, the Policeman Said (Philip K. Dick)",
        "The Chronicles of Amber (Roger Zelazny)",
        "Lord of Light (Roger Zelazny)",
        "Creatures of Light and Darkness (Roger Zelazny)",
        "Childhood's End (Arthur C. Clarke)",
        "Rendezvous with Rama (Arthur C. Clarke)",
        "2001: A Space Odyssey (Arthur C. Clarke)",
        "Foundation and Empire (Isaac Asimov)",
        "Second Foundation (Isaac Asimov)",
        "The Caves of Steel (Isaac Asimov)",
        "The Robots of Dawn (Isaac Asimov)",
        "The Shining (Stephen King)",
        "It (Stephen King)",
        "Carrie (Stephen King)",
        "The Stand (Stephen King)",
        "Misery (Stephen King)",
        "The Dark Tower: The Gunslinger (Stephen King)",
        "Salem's Lot (Stephen King)",
        "Pet Sematary (Stephen King)",
        "City (Clifford D. Simak)",
        "Way Station (Clifford D. Simak)",
        "Time and Again (Clifford D. Simak)",
        "The Goblin Reservation (Clifford D. Simak)",
        "Solaris (Stanisław Lem)",
        "The Cyberiad (Stanisław Lem)",
        "His Master's Voice (Stanisław Lem)",
        "Fiasco (Stanisław Lem)",
        "Guards! Guards! (Terry Pratchett)",
        "Mort (Terry Pratchett)",
        "The Colour of Magic (Terry Pratchett)",
        "Hogfather (Terry Pratchett)",
        "Small Gods (Terry Pratchett)",
        "The Three-Body Problem (Liu Cixin)",
        "The Dark Forest (Liu Cixin)",
        "Death's End (Liu Cixin)",
        "Slaughterhouse-Five (Kurt Vonnegut)",
        "Cat's Cradle (Kurt Vonnegut)",
        "Breakfast of Champions (Kurt Vonnegut)",
        "The Sirens of Titan (Kurt Vonnegut)",
        "God Bless You, Mr. Rosewater (Kurt Vonnegut)",
        "Around the World in Eighty Days (Jules Verne)",
        "The Mysterious Island (Jules Verne)",
        "From the Earth to the Moon (Jules Verne)",
        "Normal People (Sally Rooney)",
        "Conversations with Friends (Sally Rooney)",
        "Beautiful World, Where Are You (Sally Rooney)",
        "Make Room! Make Room! (Harry Harrison)",
        "The Stainless Steel Rat (Harry Harrison)",
        "The Stainless Steel Rat's Revenge (Harry Harrison)",
        "The Stainless Steel Rat Saves the World (Harry Harrison)",
        "Bill, the Galactic Hero (Harry Harrison)",
        "Deathworld (Harry Harrison)",
        "Deathworld 2 (Harry Harrison)",
        "Deathworld 3 (Harry Harrison)",
        "Star Smashers of the Galaxy Rangers (Harry Harrison)",
        "The Technicolor Time Machine (Harry Harrison)"
    ])
    movies: List[str] = field(default_factory=lambda: [
        "Citizen Kane (1941)",
        "Casablanca (1942)",
        "Gone with the Wind (1939)",
        "Lawrence of Arabia (1962)",
        "The Wizard of Oz (1939)",
        "On the Waterfront (1954)",
        "Singin' in the Rain (1952)",
        "It's a Wonderful Life (1946)",
        "Sunset Boulevard (1950)",
        "The Graduate (1967)",
        "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)",
        "Some Like It Hot (1959)",
        "All About Eve (1950)",
        "High Noon (1952)",
        "The Sound of Music (1965)",
        "M*A*S*H (1970)",
        "Raging Bull (1980)",
        "West Side Story (1961)",
        "To Kill a Mockingbird (1962)",
        "Chinatown (1974)",
        "The Godfather (1972)",
        "Star Wars: Episode IV - A New Hope (1977)",
        "Jaws (1975)",
        "The Shawshank Redemption (1994)",
        "Pulp Fiction (1994)",
        "The Dark Knight (2008)",
        "The Lord of the Rings: The Fellowship of the Ring (2001)",
        "The Lord of the Rings: The Return of the King (2003)",
        "The Matrix (1999)",
        "Forrest Gump (1994)",
        "Schindler's List (1993)",
        "The Silence of the Lambs (1991)",
        "Inception (2010)",
        "Fight Club (1999)",
        "Titanic (1997)",
        "Goodfellas (1990)",
        "The Empire Strikes Back (1980)",
        "The Godfather: Part II (1974)",
        "Back to the Future (1985)",
        "Jurassic Park (1993)",
        "The Lion King (1994)",
        "The Avengers (2012)",
        "Avengers: Endgame (2019)",
        "Avatar (2009)",
        "Gladiator (2000)",
        "The Social Network (2010)",
        "Interstellar (2014)",
        "Saving Private Ryan (1998)",
        "Braveheart (1995)",
        "The Green Mile (1999)",
        "The Sixth Sense (1999)",
        "American Beauty (1999)",
        "La La Land (2016)",
        "Whiplash (2014)",
        "The Grand Budapest Hotel (2014)",
        "Parasite (2019)",
        "Everything Everywhere All At Once (2022)",
        "Dune (2021)",
        "Spider-Man: No Way Home (2021)",
        "Black Panther (2018)",
        "The Batman (2022)",
        "Top Gun: Maverick (2022)",
        "Toy Story (1995)",
        "Toy Story 3 (2010)",
        "Finding Nemo (2003)",
        "The Incredibles (2004)",
        "Coco (2017)",
        "Frozen (2013)",
        "Moana (2016)",
        "Up (2009)",
        "WALL-E (2008)",
        "Ratatouille (2007)",
        "Spirited Away (2001)",
        "Howl's Moving Castle (2004)",
        "My Neighbor Totoro (1988)",
        "Akira (1988)",
        "The Shining (1980)",
        "Blade Runner (1982)",
        "Blade Runner 2049 (2017)",
        "The Big Lebowski (1998)",
        "E.T. the Extra-Terrestrial (1982)",
        "A Clockwork Orange (1971)",
        "Rocky (1976)",
        "Mad Max: Fury Road (2015)",
        "Logan (2017)",
        "Deadpool (2016)",
        "The Wolf of Wall Street (2013)",
        "Her (2013)",
        "A Star is Born (2018)",
        "Bohemian Rhapsody (2018)",
        "Slumdog Millionaire (2008)",
        "The King's Speech (2010)",
        "Argo (2012)",
        "No Country for Old Men (2007)",
        "There Will Be Blood (2007)",
        "12 Years a Slave (2013)",
        "The Revenant (2015)",
        "Birdman (2014)",
        "The Departed (2006)",
        "Memento (2000)",
        "The Prestige (2006)",
        "The Usual Suspects (1995)",
        "Seven (1995)",
        "The Hateful Eight (2015)",
        "Django Unchained (2012)",
        "Kill Bill: Vol. 1 (2003)",
        "Kill Bill: Vol. 2 (2004)",
        "Once Upon a Time in Hollywood (2019)",
        "Inglourious Basterds (2009)",
        "Harry Potter and the Sorcerer's Stone (2001)",
        "Harry Potter and the Deathly Hallows: Part 2 (2011)",
        "The Hunger Games (2012)",
        "The Twilight Saga: Breaking Dawn - Part 2 (2012)",
        "Frozen II (2019)",
        "Minions (2015)",
        "Shrek (2001)",
        "Shrek 2 (2004)",
        "2001: A Space Odyssey (1968)",
        "Psycho (1960)",
        "The Good, the Bad and the Ugly (1966)",
        "Apocalypse Now (1979)",
        "Taxi Driver (1976)",
        "Alien (1979)",
        "Raiders of the Lost Ark (1981)",
        "Terminator 2: Judgment Day (1991)",
        "Se7en (1995)",
        "Fargo (1996)",
        "Good Will Hunting (1997)",
        "L.A. Confidential (1997)",
        "The Truman Show (1998)",
        "American History X (1998)",
        "Being John Malkovich (1999)",
        "Magnolia (1999)",
        "Almost Famous (2000)",
        "Requiem for a Dream (2000)",
        "Donnie Darko (2001)",
        "Eternal Sunshine of the Spotless Mind (2004)",
        "Children of Men (2006)",
        "Pan's Labyrinth (2006)",
        "Zodiac (2007)",
        "Black Swan (2010)",
        "Drive (2011)",
        "The Artist (2011)",
        "Moonrise Kingdom (2012)",
        "Silver Linings Playbook (2012)",
        "Spotlight (2015)",
        "Arrival (2016)",
        "Get Out (2017)",
        "Call Me by Your Name (2017)",
        "Lady Bird (2017)",
        "1917 (2019)",
        "Knives Out (2019)"
    ])
